### ISSUE TITLE
Problemas na configuração da aplicação

### ISSUE THREAD

**Issue by ricardommoreira** [forpdi/plataforma-for#276]
Olá pessoal, instalo a ferramenta conforme documento de referência, porém quando vou acessar a aplicação obtenho a seguinte mensagem de erro do servidor de aplicação.

09:34:30,172 ERROR [io.undertow.request] (default task-1) UT005023: Exception handling request to /forpdi/WEB-INF/jsp/index/index.jsp: javax.servlet.ServletException: /WEB-INF/jsp/index/index.jsp raised an exception
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:127)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:58)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:72)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.SecurityInitialHandler.handleRequest(SecurityInitialHandler.java:76)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:282)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:261)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:80)
        at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:172)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:199)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:774)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.servlet.ServletException: javax.servlet.jsp.JspException: java.io.FileNotFoundException: /index.html
        at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:844)
        at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:777)
        at org.apache.jsp.WEB_002dINF.jsp.index.index_jsp._jspService(index_jsp.java:67)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:69)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:366)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:326)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:259)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:130)
        at br.com.caelum.vraptor.core.DefaultStaticContentHandler.deferProcessingToContainer(DefaultStaticContentHandler.java:87)
        at br.com.caelum.vraptor.core.DefaultStaticContentHandler$Proxy$_$$_WeldClientProxy.deferProcessingToContainer(Unknown Source)
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:114)
        at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:60)
        at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:132)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:85)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.jsp.JspFileHandler.handleRequest(JspFileHandler.java:32)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToPath(ServletInitialHandler.java:198)
        at io.undertow.servlet.spec.RequestDispatcherImpl.forwardImpl(RequestDispatcherImpl.java:195)
        at io.undertow.servlet.spec.RequestDispatcherImpl.forward(RequestDispatcherImpl.java:108)
        at br.com.caelum.vraptor.view.DefaultPageResult.defaultView(DefaultPageResult.java:81)
        at br.com.caelum.vraptor.observer.ForwardToDefaultView.forward(ForwardToDefaultView.java:67)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
        at br.com.caelum.vraptor.observer.RequestHandlerObserver.handle(RequestHandlerObserver.java:94)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:88)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:78)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:129)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:306)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:284)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:262)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:271)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:260)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:89)
        at br.com.caelum.vraptor.VRaptor.doFilter(VRaptor.java:123)
        ... 29 more
Caused by: java.io.FileNotFoundException: /index.html
        at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:153)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:86)
        at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:82)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToServlet(ServletInitialHandler.java:208)
        at io.undertow.servlet.spec.RequestDispatcherImpl.includeImpl(RequestDispatcherImpl.java:345)
        at io.undertow.servlet.spec.RequestDispatcherImpl.include(RequestDispatcherImpl.java:258)
        at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:322)
        at org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:173)
        at org.apache.jsp.WEB_002dINF.jsp.index.index_jsp._jspx_meth_c_005fimport_005f0(index_jsp.java:87)
        at org.apache.jsp.WEB_002dINF.jsp.index.index_jsp._jspService(index_jsp.java:60)

**Comment by caiosabadin** [comment]
Passo pelo mesmo problema que o descrito por você. Na esperança de que isso se devia ao fato de que o programa precisa do front-end configurado no Apache, configurei-o como proxy, conforme o README, mas, ainda assim, ao tentar acessar localhost/forpdi, ele tenta chamar um script environment que não existe e que não consigo achar em lugar algum do projeto.

**Comment by renatorroliveira** [comment]
@ricardommoreira você está acessando o backend diretamente, ele não possui UI, apenas API REST. Você precisa configurar o frontend como um proxy conforme o @caiosabadin disse.

@caiosabadin No seu caso, o problema está na questão do proxy. A sua configuração do proxy provavelmente não funcionou corretamente, o seu Apache não está conseguindo acessar a API do backend. `environment` é um endpoint do backend que retorna as configurações de ambiente para que o frontend funcione corretamente com a API

**Comment by renatorroliveira** [comment]
Estou tentando voltar a dar o suporte aqui, portanto devo conseguir responder às questões diariamente. O único porém é que estou em outro fuso horário (GMT-7) então devo responder somente à noite.

**Comment by caiosabadin** [comment]
> @ricardommoreira você está acessando o backend diretamente, ele não possui UI, apenas API REST. Você precisa configurar o frontend como um proxy conforme o @caiosabadin disse.
> 
> @caiosabadin No seu caso, o problema está na questão do proxy. A sua configuração do proxy provavelmente não funcionou corretamente, o seu Apache não está conseguindo acessar a API do backend. `environment` é um endpoint do backend que retorna as configurações de ambiente para que o frontend funcione corretamente com a API

Obrigado por sua resposta, Renato :smile: Vou abrir uma nova issue então, conforme minhas configurações, para ver onde estou errando...

**Comment by ifgoias** [comment]
Opa, obrigado pela resposta.. mudei de estratégia, subi a aplicação via docker. :)
