### ISSUE TITLE
Ajuda na configuração da aplicação

### ISSUE THREAD

**Issue by nathaniel1978** [forpdi/plataforma-for#278]
Bom dia caros colegas,
Gostaria de saber se existe algum material especifico que auxilie na implantação da aplicação? Já tentei várias vezes seguir a orientação do git e não obtive sucesso.

**Comment by rainerdepaula** [comment]
Estamos também enfrentando um problema na implantação da nova versão. @renatorroliveira pode nos ajudar

> [root@forpdi frontend-web]# npm install
> npm WARN deprecated mdi@1.9.33: The mdi package was renamed to @mdi/font after v2.2.43. Please rename in your package.json for future updates.
> npm WARN deprecated flatten@1.0.2: I wrote this module a very long time ago; you should use something else.
> 
> > node-sass@4.12.0 install /opt/forpdi/frontend-web/node_modules/node-sass
> > node scripts/install.js
> 
> sh: node: command not found
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! file sh
> npm ERR! code ELIFECYCLE
> npm ERR! errno ENOENT
> npm ERR! syscall spawn
> npm ERR! node-sass@4.12.0 install: `node scripts/install.js`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the node-sass@4.12.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2019-07-17T17_39_15_995Z-debug.log
>

**Comment by nathaniel1978** [comment]
E que já estou tentando a algum tempo e sem êxito! Irei aguardar mas agradeceria a ajuda dos colegas na implantação do sistema.

**Comment by nathaniel1978** [comment]
Boa tarde caro Rainer, existe a possibilidade de entrar em contato com o sr. Também sou servidor federal precisando de uma ajudinha.

**Comment by rainerdepaula** [comment]
> Boa tarde caro Rainer, existe a possibilidade de entrar em contato com o sr. Também sou servidor federal precisando de uma ajudinha.

Estamos tentando resolver o problema aqui de instalação, se conseguirmos te aviso.

**Comment by nathaniel1978** [comment]
Obrigado pela sua disposição!

**Comment by renatorroliveira** [comment]
Pessoal, desculpem eu não ter respondido antes. Estive ocupado e sem tempo para ajudar. Vou tentar responder e corrigir alguns problemas de código nas próximas semanas/meses.

A implantação teoricamente continua igual ao que era antes da implementação do ForRisco.

@rainerdepaula por alguma razão o comando `node` não está sendo encontrado em seu sistema. Provavelmente a variável de ambiente `PATH` não está disponível quando o `node-sass` tentar excutar o script. Normalmente a melhor prática é colocar o comando export com o caminho do nodejs em um novo arquivo por exemplo `/etc/profile.d/nodejs.sh`.

@nathaniel1978 Preciso de mais informações para te ajudar.

**Comment by rainerdepaula** [comment]
Conseguimos instalar porém as imagens (foto de perfil, etc), ao tentar salvar, no log aparece que estão sendo enviadas para cloud.progolden.com.br e não grava.

**Comment by nathaniel1978** [comment]
Boa tarde Rainer,
Teria como me ajudar nesse processo de implantação, as etapas que realizou. Desde já agradeço atenção.

**Comment by renatorroliveira** [comment]
@rainerdepaula sim, utilizávamos esse serviço para armazenamento das imagens. No caso isso é uma das alterações que precisa ser feita no código para tornar o sistema 100% independente.

@nathaniel1978 você prefere realizar a publicação via Docker? Existe um pull request em andamento onde estou implementando os dockerfiles para isso.

Poste aqui mais detalhes do que você já conseguiu fazer e o que não está funcionando para que possamos te ajudar.

**Comment by nathaniel1978** [comment]
![erro-forpdi](https://user-images.githubusercontent.com/51493779/61715159-784c2a80-ad2a-11e9-8bc0-0062c80a0213.PNG)

**Comment by leandropereiraifmg** [comment]
> Boa tarde Rainer,
> Teria como me ajudar nesse processo de implantação, as etapas que realizou. Desde já agradeço atenção.

Olá @nathaniel1978 
Para instalar o JAVA o Maven e o wildfly, pode ser seguido os tutorias da internet.
Estou usando o centos 7
Deve-se usar o nvm para instalar o node. (versão 10 ou 11 no máximo, 12 não funciona)
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
Sair do prompt ou recarregar o bash para o comando nvm ficar ativo
#eu usei o node versão 11
nvm install 11

git clone https://github.com/forpdi/plataforma-for.git (download do forpdi, descompacta dentro de opt/
   cd /opt/plataforma-for/frontend-web/
   npm install --unsafe-perm --save-dev -g node-sass webpack webpack-cli 
   npm install --unsafe-perm --save-dev -D webpack
   npm run build

#instalando o Apache-MAVEN_HOME
wget http://ftp.unicamp.br/pub/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
 tar -zxvf apache-maven-3.6.1-bin.tar.gz
#renomeando (deve estar dentro de opt/ também
mv apache-maven-3.6.1 maven


criar um arquivo com os PATH (vi /etc/profile.d/maven)

#para java 8 no centos 7
JAVA_HOME=/usr/lib/jvm/java-8-oracle
export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}

#carregar as configurações do PATH
source /etc/profile.d/maven
mvn -v (esse comando deve mostra as informações abaixo)
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T16:00:29-03:00)
Maven home: /opt/maven
Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.212.b04-0.el7_6.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.21.3.el7.x86_64", arch: "amd64", family: "unix"

**Comment by nathaniel1978** [comment]
Ainda não obtive sucesso, segue a sequência da minha instação:

**************************************************************		
 		SEQUENCIA DE INSTALAÇÃO 
**************************************************************

********** SERVIDOR CENTOS 7 ***********
1 - CONFIGURAÇÃO:
yum -y update
systemctl stop firewalld
systemctl disable firewalld
vi /etc/sysconfig/selinux

SELINUX=disabled

******** JAVA *********
1 - BAIXA JAVA ORACLE
jdk-8u221-linux-x64.rpm
2 - INSTALAÇÃO
cd /usr/java
rpm -ivh jdk-8u221-linux-x64.rpm
3 - VERIFICANDO INSTALAÇÃO
java -version
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

********** INSTALAR O MAVEN *************
Link: https://linuxize.com/post/how-to-install-apache-maven-on-centos-7/
1 - DOWNLOAD E DESCOMPACTAÇÃO:
wget https://www-us.apache.org/dist/maven/maven-3/3.6.0/binaries/apache-maven-3.6.0-bin.tar.gz -P /tmp
sudo tar xf /tmp/apache-maven-3.6.0.tar.gz -C /opt
sudo ln -s /opt/apache-maven-3.6.0 /opt/maven
2 - CONFIGURANDO PATH:
sudo nano /etc/profile.d/maven.sh

export JAVA_HOME=/usr/java/jdk1.8.0_221-amd64
export M2_HOME=/opt/maven
export MAVEN_HOME=/opt/maven
export PATH=${M2_HOME}/bin:${PATH}

3 - PERMISSÃO PARA EXECUTAR:
sudo chmod +x /etc/profile.d/maven.sh
source /etc/profile.d/maven.sh

4 - VERIFICANDO A INSTALAÇÃO:
mvn -version

Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T14:41:47-04:00)
Maven home: /opt/maven
Java version: 1.8.0_221, vendor: Oracle Corporation, runtime: /usr/java/jdk1.8.0_221-amd64/jre
Default locale: pt_BR, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-957.el7.x86_64", arch: "amd64", family: "unix"

************** INSTALANDO NODE ***********
Link: https://tecadmin.net/install-latest-nodejs-and-npm-on-centos/

1 - CONFIGURAÇÃO
yum install -y gcc-c++ make
curl -sL https://rpm.nodesource.com/setup_11.x | sudo -E bash -

2 - INSTALAÇÃO
sudo yum install nodejs

3 - VERIFICANDO A INSTALÇÃO
node -v

v11.15.0

npm -v

6.7.0

******************* WILDFLY ***************
Link: https://giovannireisnunes.wordpress.com/2015/08/21/instalando-wildfly-no-centos/

1 - DOWNLOAD E CONFIGURAÇÃO:
cd /opt/
wget https://download.jboss.org/wildfly/9.0.2.Final/wildfly-9.0.2.Final.zip
unzip wildfly-9.0.2.Final.zip
mv wildfly-9.0.2.Final.zip wildfly

2 - ADICIONANDO USUÁRIO:
useradd -s /usr/sbin/nologin wildfly
chown -R wildfly /opt/wildfly

3 - CONFIGURANDO WILDFLY:
cd /opt/wildfly-9.0.1.Final/bin
./add-user.sh

-> usuario criado: forpdi

4 - ADICIONANDO WILDFLY NA INICIALIZAÇÃO:
cd /etc/init.d
ln -s /opt/wildfly/bin/init.d/wildfly-init-redhat.sh wildfly

cd /etc/default
ln -s /opt/wildfly/bin/init.d/wildfly.conf

5 - CONFIGURANDO WILDFLY:
vim /opt/wildfly/bin/init.d/wildfly.conf

-> removendo comentário: JBOSS_USER=wildfly
-> adicionando linha no final: JBOSS_OPTS="-b 0.0.0.0 -bmanagement=0.0.0.0"

service wildfly start
chkconfig wildfly on

**************** INSTALANDO MYSQL 5.7 ****************
Link: https://tecadmin.net/install-mysql-5-7-centos-rhel/

1 - REPOSITÓRIO:
yum localinstall https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm

2 - INSTALAÇÃO E CONFIGURAÇÃO:
yum install mysql-community-server
systemctl start mysqld
systemctl enable msyqld

3 - ADICIONANDO BASE FORPDI NO MYSQL:
CREATE DATABASE forpdi_prd CHARSET=utf8;

*************** CONFIGURANDO FORPDI SEGUINDO GIT *************
1 - FRONTEND:
cd frontend-web
npm install

npm run build

2 - BACKEND:
2.1 - CONFIGURANDO dev.properties:
cd /opt/plataforma-for/backend-java/
cp prd.properties

war.frontenddir=development
backendUrl=http://localhost:8080/forpdi/

db.host=localhost
db.port=3306
db.name=forpdi_prd
db.username=root
db.password=Sql123!@#

mail.smtp.from.name=ForPDI
mail.smtp.from.email=noreply@forpdi.org
mail.smtp.url=localhost
mail.smtp.port=25
mail.smtp.username=
mail.smtp.password=
mail.smtp.ssl=false
mail.smtp.tls=false

store.pdfs=./temp
store.files=/var/forpdi/files/

cd /opt/plataforma-for/backend-java/
mvn clean package -P prd

3 - COPIANDO 
cp /opt/plataforma-for/backend-java/target/forpdi.war /opt/wildfly/standalone/deployments/

4 - CONFIGURANDO ARQUIVO standalone.xml:
vi /opt/wildfly/standalone/configuration/standalone.xml

<ajp-listener name="default-ajp" socket-binding="ajp" redirect-socket="http"/>

5 - RESTARTANDO SERVIÇO WILDFLY:
service wildfly restart

******************* CONFIGURAÇÕES FORPDI GIT *****************


**************************************************************
			ERROS
**************************************************************
1 - COMANDO TAIL NO ARQUIVO LOG DO WILDFLY:
tail -f server.log

 at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:263)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchToServlet(ServletInitialHandler.java:208)
        at io.undertow.servlet.spec.RequestDispatcherImpl.includeImpl(RequestDispatcherImpl.java:345)
        at io.undertow.servlet.spec.RequestDispatcherImpl.include(RequestDispatcherImpl.java:258)
        at org.apache.taglibs.standard.tag.common.core.ImportSupport.acquireString(ImportSupport.java:322)
        at org.apache.taglibs.standard.tag.common.core.ImportSupport.doEndTag(ImportSupport.java:173)
        at org.apache.jsp.WEB_002dINF.jsp.index.index_jsp._jspx_meth_c_005fimport_005f0(index_jsp.java:87)
        at org.apache.jsp.WEB_002dINF.jsp.index.index_jsp._jspService(index_jsp.java:60)
        ... 83 more

2 - NAVEGADOR

Link: http://meu-endereco:8080/forpdi/

3 - ERRO NA PÁGINA:
Internal Server Error

4 - SITUAÇÃO NO WILDFLY:
![situacao-wildfly-forpdi](https://user-images.githubusercontent.com/51493779/61746112-f6c7bd00-ad68-11e9-88e7-2af26abab2fb.PNG)

**Comment by arthurd2** [comment]
Salve @nathaniel1978 , lancei um Merge Request recentemente que possibilitar subir toda a infra em Docker com apenas um comando, se quiser testar fique a vontade. =D
MR: https://github.com/forpdi/plataforma-for/pull/282
Branch: https://github.com/arthurd2/plataforma-for/tree/docker-support

**Comment by nathaniel1978** [comment]
Boa tarde,
Muito obrigado @arthurd2 , sim testarei no docker!

**Comment by renatorroliveira** [comment]
@nathaniel1978 provavelmente seu deployment está funcionando, veja a conclusão da issue #280 

Por favor, diga se conseguiu com o docker, estou testando esse pull request para incluí-lo no repositório principal.

**Comment by nathaniel1978** [comment]
Boa tarde amigos,
Depois do sofrimento que passei para tentar subir o serviço fiz um tutorial destinado a CENTOS 7 e espero que ajude os colegas que tem a mesma dificuldade.
[tutorial forpdi centos 7.pdf](https://github.com/forpdi/plataforma-for/files/3597761/tutorial.forpdi.centos.7.pdf)

**Comment by samuelclerod** [comment]
> Salve @nathaniel1978 , lancei um Merge Request recentemente que possibilitar subir toda a infra em Docker com apenas um comando, se quiser testar fique a vontade. =D
> MR: #282
> Branch: https://github.com/arthurd2/plataforma-for/tree/docker-support



> @nathaniel1978 provavelmente seu deployment está funcionando, veja a conclusão da issue #280
> 
> Por favor, diga se conseguiu com o docker, estou testando esse pull request para incluí-lo no repositório principal.

> > Salve @caiosabadin , lancei um Merge Request recentemente que possibilitar subir toda a infra em Docker com apenas um comando, se quiser testar fique a vontade. =D
> > MR: #282
> > Branch: https://github.com/arthurd2/plataforma-for/tree/docker-support
> 
> Olá, @arthurd2
> Venho aqui acompanhando os posts e estou precisando subir individualmente um container do FrontEnd. Já tentei vários caminhos. Sou fã do Docker, mas ainda n tive êxito. Testei a branch master e a sua tb. Creio que seja algum detalhe na configuração. Quanto ao Back consegui subir separado, mas ainda está na minha IDE, enquanto isso já queria ver o front rodando. Quando possível, estamos muito precisando de ajuda para essa aplicação.

Bom dia Pessoal, 
Tive um problema ao subir o ambiente com Docker (do repositório @arthurd2 também), e aqui na UFCA temos preferência por subir nossas aplicações em containers. O erro tinha algo relacionado ao undertow com docker, e o suporte a IPV6 de alguns S.O.s . Ao verificar erro similar em [https://github.com/jboss-dockerfiles/jbpm/issues/26,](https://github.com/jboss-dockerfiles/jbpm/issues/26) passei o argumento `"-Djava.net.preferIPv4Stack=true" ` para JVM e funcionou. 
O docker-compose.yml ficou assim:
```
[...]
forpdi-backend:
  build: ./backend-java
    image: platfor-backend
    volumes:
      - pdfs:/var/forpdi/pdfs
      - arquivos:/var/forpdi/files
    depends_on:
      - forpdi-database
    ports:
      - 8009:8009
      - 8080:8080
    environment: 
      - "JAVA_OPTS=-Djava.net.preferIPv4Stack=true"
[...]
```
